### PR TITLE
Change talks order

### PR DESCRIPTION
**Pull request by filipebarcos**
Not sure if y'all agree, but since we had the functional talk before the AMS one, I think this order would be better.

In other words, ordered by talk date, instead of "agreement date".

### CODE REVIEW

**Comment by franzejr** [comment]
But the Functional talk is already the number 3.

**Comment by franzejr** [comment]
We can change the order in the website, but the number will be the same, what do you think?

**Comment by filipebarcos** [comment]
Oh, you mean in google+? If we can't change that, it will suck big time.

**Comment by franzejr** [comment]
@filipebarcos, you are right. I will change the talks number as well.

**Pull request merged**
